# Generated by Django 3.2.25 on 2025-02-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileshare',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='shareablelink',
            name='max_access',
        ),
        migrations.AddField(
            model_name='fileshare',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='is_link_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='one_time_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='share_link',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='one_time_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'View Only'), ('DOWNLOAD', 'View and Download'), ('EDIT', 'Edit and Download')], default='VIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
