# Generated by Django 3.2.25 on 2025-02-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_auto_20250209_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablelink',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'View Only'), ('DOWNLOAD', 'Download')], default='VIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='shareablelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareablelink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.encryptedfile'),
        ),
    ]
